import { v4 as uuidv4 } from "uuid";
import {
  partnetLogo1,
  partnetLogo10,
  partnetLogo11,
  partnetLogo2,
  partnetLogo3,
  partnetLogo4,
  partnetLogo5,
  partnetLogo6,
  partnetLogo7,
  partnetLogo8,
  partnetLogo9,
} from "../components/Image/Image";

export const partnersLogo = Object.freeze([
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo1,
    alt: "partnerLogo1",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo2,
    alt: "partnerLogo2",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo3,
    alt: "partnetLogo3",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo4,
    alt: "partnetLogo4",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo5,
    alt: "partnetLogo5",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo6,
    alt: "partnetLogo6",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo7,
    alt: "partnetLogo7",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo8,
    alt: "partnetLogo8",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo9,
    alt: "partnetLogo9",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo10,
    alt: "partnetLogo10",
    link: "/",
  },
  {
    id: uuidv4(),
    className: "partnersLogo",
    src: partnetLogo11,
    alt: "partnetLogo11",
    link: "/",
  },
]);
